coverage:
  precision: 1
  round: up
  range: "70...100"

  status:
    project:
      default: on
    patch:
      default: on
    changes:
      default: off

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "3rdparty/googletest/googletest/include/gtest/gtest.h"
  - "3rdparty/googletest/googletest/include/gtest/gtest-message.h"
  - "3rdparty/googletest/googletest/include/gtest/gtest-printers.h"
  - "3rdparty/googletest/googletest/include/gtest/internal/gtest-internal.h"
  - "3rdparty/googletest/googletest/include/gtest/internal/gtest-port.h"
  - "3rdparty/libfor/for-gen.c"
  - "3rdparty/libfor/for.c"
  - "3rdparty/liblzf/lzf_c.c"
  - "3rdparty/liblzf/lzf_d.c"
  - "3rdparty/catch/catch.hpp"
  - "3rdparty/libvbyte/vbyte.cc"
  - "3rdparty/murmurhash3/MurmurHash3.cc"

