language: cpp
compiler:
  - gcc



before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17
  #  - sudo apt-get install -qq g++-7
  #  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90


addons: 
  apt: 
    packages: libboost-all-dev

script: ./build-all.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)


notifications:
   email: false


